### ISSUE TITLE
pip install wooey fails:  No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by magelan** [wooey/django-djangui#22]
Hi,

running pip install wooey fails with error:

Downloading/unpacking wooey
  Downloading Wooey-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_reinhard/wooey/setup.py) egg_info for package wooey
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_reinhard/wooey/setup.py", line 3, in <module>
        with open('README.md') as readme:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_reinhard/wooey/setup.py", line 3, in <module>

```
with open('README.md') as readme:
```

IOError: [Errno 2] No such file or directory: 'README.md'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_reinhard/wooey
Storing debug log for failure in /tmp/tmpleVwXi

**Comment by Chris7** [comment]
What does the debug log say?

**Comment by armedgorillas** [comment]
I received the same error, and this is the verbose version. Does this help circumscribe the problem?

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z6ivf1_8/wooey
Collecting wooey
  Getting page https://pypi.python.org/simple/wooey/
  1 location(s) to search for versions of wooey:
  * https://pypi.python.org/simple/wooey/
  Getting page https://pypi.python.org/simple/wooey/
  Analyzing links from page https://pypi.python.org/simple/wooey/
    Found link https://pypi.python.org/packages/source/W/Wooey/Wooey-0.0.1.tar.gz#md5=0ad4fb5e77e60019c536c899cf409ec4 (from https://pypi.python.org/simple/wooey/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/W/Wooey/Wooey-0.0.2.tar.gz#md5=572147eb21a8131511e98db59de2715c (from https://pypi.python.org/simple/wooey/), version: 0.0.2
    Found link https://pypi.python.org/packages/source/W/Wooey/Wooey-0.0.3.tar.gz#md5=38fab6e75bc34cc95faa23b3ac52df0f (from https://pypi.python.org/simple/wooey/), version: 0.0.3
    Found link https://pypi.python.org/packages/source/W/Wooey/Wooey-0.0.4.tar.gz#md5=5b18e26c0102a7aa95ed0a608253c3f6 (from https://pypi.python.org/simple/wooey/), version: 0.0.4
  Using version 0.0.4 (newest of versions: 0.0.4, 0.0.3, 0.0.2, 0.0.1)
  Using cached Wooey-0.0.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/W/Wooey/Wooey-0.0.4.tar.gz#md5=5b18e26c0102a7aa95ed0a608253c3f6 (from https://pypi.python.org/simple/wooey/)
  Running setup.py (path:/tmp/pip-build-ffcsltgo/wooey/setup.py) egg_info for package wooey
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ffcsltgo/wooey/setup.py", line 3, in <module>
        with open('README.md') as readme:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ffcsltgo/wooey/setup.py", line 3, in <module>
        with open('README.md') as readme:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ffcsltgo/wooey
Exception information:
Traceback (most recent call last):
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/commands/install.py", line 282, in run
    requirement_set.prepare_files(finder)
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/req/req_install.py", line 407, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/app/webstart/html/webstart/anaconda3/envs/wooey_env/lib/python3.4/site-packages/pip/utils/__init__.py", line 732, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ffcsltgo/wooey
```

**Comment by Chris7** [comment]
This is actually the django-djangui repo. But I looked at the file on pypi and it's not including a lot of extra files because its MANIFEST is missing. I don't control wooey on pypi at the moment, so @mfitzp will need to fix the manifest to include the missing files. You can alternatively install from the github repo through pip as well:
pip install git+https://github.com/wooey/Wooey.git

**Comment by mfitzp** [comment]
Thanks :)

Not sure whether it's worth fixing it since it should (hopefully) be
replaced within a few days.

**Comment by mfitzp** [comment]
@Chris7 I've added you as package owner on PyPi so we can both manage releases.

I'll close this as it relates to the old Wooey and will be solved with the combined release.
